package be.kdg.integration.gameapplication.model.authservices.services;

/**
 * Defines a contract, that implementing class has to be able to generate salt,
 * convert it to string and shuffle it with users password and encode it
 * @see PasswordService
 */
public interface PasswordEncoder{

    /**
     * Generates an array of randomly generated bytes
     * @return a random salt as an array of bytes
     */
    byte[] generateSalt();

    /**
     * Converts byte array salt to string
     * @param salt in a byte format
     * @return salt in a string format
     */
    String saltToString(byte[] salt);


    /**
     * Generates a salt as a string
     * @return salt in a string format
     */
    String generateSaltAsString();

    /**
     * Takes user's raw password, shuffles it with salt and encodes it
     * @param rawPassword user's input
     * @param salt the Base64-encoded salt in string format to combine with the password
     * @return completely encoded password String
     * @throws PasswordServiceException if hashing fails
     */
    String addSaltToPasswordAndEncodeIt(String rawPassword, String salt) throws PasswordServiceException;
}
