const vocabularyData = {
    EN: {
        "menu-item-home":           "Home",
        "menu-item-team":           "Team",
        "menu-item-gallery":        "Gallery",
        "menu-item-guidelines":     "Guidelines",
        "menu-item-implementation": "Implementation",
        "menu-item-ai":             "AI",
        "menu-item-stats":          "Stats",
        "menu-item-feedback":       "Feedback",

        "team-page-header":                       "Our Team",
        "team-page-yurii-desc": "Special skill: \n \n Disagreed with the compiler. \n The compiler was wrong.",
        "team-page-taras-desc": "Special skill: \n \n Once fixed a bug by staring at it long enough.",
        "team-page-omer-desc": "Special skill: \n \n Has never read the documentation. \n Has never needed to.",
        "team-page-ronan-desc": "Special skill: \n \n Types very fast. \n This has not been proven to help.",
        "team-page-decision-insights-header":     "Team insight",
        "team-page-decision-insights":            "We all wear glasses to look smart.",
        "team-page-decision-decisions-header":    "The way we make decisions",
        "team-page-decision-decisions":           "Usually we just throw a die, and then we make a decision about the project based on that. We found this approach much easier than long discussions.",
        "team-page-decision-working-flow-header": "Working flow",
        "team-page-decision-working-flow":        "We open our laptops, stare at the screen for a while, and eventually something works. We have not yet figured out why.",
        "team-page-how-made-header": "How we make our project",

        "ai-logic-page-header":           "How did we make it possible?",
        "ai-logic-page-approaches-header": "Approaches",
        "ai-logic-page-smart-header":      "SMART",
        "ai-logic-page-smart-list-item-1": "Complicated algorithm behind it",
        "ai-logic-page-smart-list-item-2": "Hard probability calculations based on danger evaluation",
        "ai-logic-page-smart-list-item-3": "Future prediction",
        "ai-logic-page-smart-list-item-4": "Used in competitive and custom matches",
        "ai-logic-page-smart-list-item-5": "Losing or winning it in competitive affects the leaderboard",
        "ai-logic-page-smart-list-item-6": "Prepare yourself in custom non-ranked game simulation",
        "ai-logic-page-random-header":     "RANDOM",
        "ai-logic-page-random-list-item-1": "Validation move algorithm",
        "ai-logic-page-random-list-item-2": "Pure entropy",
        "ai-logic-page-random-list-item-3": "The most unexpected decisions",
        "ai-logic-page-random-list-item-4": "Created mostly for fun",
        "ai-logic-page-random-list-item-5": "Has no impact on your score",
        "ai-logic-page-random-list-item-6": "Available only in custom match",

        "implementation-page-header":       "Implementation",
        "implementation-page-intro":        "Our game was implemented as a JavaFX application in alignment with the MVP patterns.",
        "implementation-page-domain-header": "Domain Model",
        "implementation-page-domain-desc":  "The domain model shows the overview of our model.",
        "implementation-page-resources-header": "Resources and Expertise Used",
        "implementation-page-resources-dt-1": "Game design and balancing",
        "implementation-page-resources-dd-1": "We turned the board game rules into clear digital rules and made sure the edge cases will not break the game.",
        "implementation-page-resources-dt-2": "Object-oriented programming",
        "implementation-page-resources-dd-2": "We separated the code into objects with responsibilities, so move logic, scoring, and AI are easier to read and update.",
        "implementation-page-resources-dt-3": "Data handling",
        "implementation-page-resources-dd-3": "Game results and moves are stored in a structured way, which lets us build the stats view on the website and leaderboard in-game.",
        "implementation-page-notes-header": "Implementation Notes",
        "implementation-page-notes-p1":     "Smart AI was implemented to challenge the player, while Easy AI is completely unpredictable and can be used to get to know the game more.",
        "implementation-page-notes-p2":     "Moves are logged as structured so they can be sent to the webpage \"Stats\".",

        "feedback-page-header":            "Feedback",
        "feedback-page-intro":             "We are first year students who really value the feedback we get from you. If you have any suggestions or feedback regarding our game or website, we would love to hear it. Thanks and have fun.",
        "feedback-page-form-header":       "Give feedback",
        "feedback-page-legend-personal":   "Personal Information",
        "feedback-page-label-name":        "Name:",
        "feedback-page-placeholder-name":  "e.g. John Doe",
        "feedback-page-label-phone":       "Phone Number:",
        "feedback-page-placeholder-phone": "e.g. +32 123 45 67 89",
        "feedback-page-label-email":       "Email address:",
        "feedback-page-placeholder-email": "e.g. info@zaroc.com",
        "feedback-page-legend-feedback":   "Your feedback",
        "feedback-page-label-type":        "What's the feedback about?",
        "feedback-page-option-gameplay":   "Gameplay",
        "feedback-page-option-website":    "Website",
        "feedback-page-option-other":      "Other",
        "feedback-page-label-feedback":    "Feedback:",
        "feedback-page-submit":            "Submit",

        "gallery-page-header":    "Screenshots & Media",
        "gallery-page-caption-1": "The calm before the storm.",
        "gallery-page-caption-2": "Pick your poison",
        "gallery-page-caption-3": "Captcha included",
        "gallery-page-caption-4": "Can you reach the top?",
        "gallery-page-caption-5": "It's not luck. (It's luck.)",
        "gallery-page-caption-6": "To remind of your failures",
        "gallery-page-alt-1":     "login screen",
        "gallery-page-alt-2":     "game selection",
        "gallery-page-alt-3":     "login screen",
        "gallery-page-alt-4":     "leaderboard",
        "gallery-page-alt-5":     "game screen",
        "gallery-page-alt-6":     "games overview",

        "guidelines-page-game-rules-header":    "Game Rules",
        "guidelines-page-setup-header":         "The beginning of the game",
        "guidelines-page-setup-desc":           "The board has three rows of pegs: 5 short, 4 medium and 4 long. Press them into their rows from front to back. Thread all 16 pieces onto the 4 long pegs, alternating dark and light, 4 pieces per peg.",
        "guidelines-page-objective-header":     "Objective",
        "guidelines-page-objective-desc":       "Be the first player to get at least 3 pieces of your color into the 5 indentations at the front of the board.",
        "guidelines-page-how-to-play-header":   "How to play",
        "guidelines-page-how-dt-1":             "Piece colors do not matter!",
        "guidelines-page-how-dd-1":             "Each turn consists of exactly two moves. You can move pieces of either color on your turn.",
        "guidelines-page-how-dt-2":             "Sideways move",
        "guidelines-page-how-dd-2":             "Move the top piece to an adjacent peg of the same height, as long as there is space. You cannot immediately undo the move you just made.",
        "guidelines-page-how-dt-3":             "How to move forward?",
        "guidelines-page-how-dd-3":             "Move the top piece forward to a lower peg or indentation, following the arrows on the board. This is only allowed if the piece is at the very top of its peg with no room above it.",
        "guidelines-page-how-dt-4":             "Back in time!",
        "guidelines-page-how-dd-4":             "You can undo your move! Be aware, you have only 3 undos per game. Not using undos increases points you get or lose",
        "guidelines-page-restrictions-header":  "Restrictions",
        "guidelines-page-restrictions-li-1":    "Once a piece reaches the front indentations it cannot move again.",
        "guidelines-page-restrictions-li-2":    "Backward moves are not allowed.",
        "guidelines-page-restrictions-li-3":    "The last piece moved cannot be moved back to where it came from, even by the other player.",
        "guidelines-page-winning-header":       "Winning",
        "guidelines-page-winning-desc":         "The first player to have 3 pieces of their color in the front indentations wins the game.",
        "guidelines-page-installation-header":  "Installation Instructions",
        "guidelines-page-installation-li-1":    "Open your browser (You are here)",
        "guidelines-page-installation-li-2":    "Navigate to the main page (After you read all instructions)",
        "guidelines-page-installation-li-3":    "Download game and open it",
        "guidelines-page-installation-li-4":    "Enter as a guest or register account to gain more experience",
        "guidelines-page-installation-li-5":    "Have fun!",
        "guidelines-page-technical-header":     "Technical Requirements",
        "guidelines-page-technical-dt-1":       "Computer",
        "guidelines-page-technical-dd-1":       "The game is only available for PC-users",
        "guidelines-page-technical-dt-2":       "JVM",
        "guidelines-page-technical-dd-2":       "You must have Java Virtual Machine installed on your PC",
        "guidelines-page-technical-dt-3":       "Internet connection",
        "guidelines-page-technical-dd-3":       "Non-essential requirement, but needed if you want to be part of leaderboard and save your progress as well as your settings",

        "stats-page-analysis-header":     "Analyzing data",
        "stats-page-analysis-desc":       "We gathered certain information according to players' gameplay style and conducted regression and correlation analysis",
        "stats-page-workflow-caption":    "Visual representation of data exploration model",
        "stats-page-correlation-caption": "Visual representation of correlation",
        "stats-page-numbers-dt":          "What do the numbers say?",
        "stats-page-numbers-dd":          "RMSE above 65 indicates high data dispersion, which is confirmed by the correlation and regression models.",
        "stats-page-notes-dt":            "Interesting notes",
        "stats-page-notes-dd":            "The dataset covers 50 games but only 5 players, which limits its scalability. The model without outliers, despite a lower correlation ratio, has a higher R² and is therefore more representative.",
        "stats-page-conclusion-header":   "Conclusion",
        "stats-page-conclusion-desc-before": "There is no strong correlation between player skill and time to make a move. After researching the roots of this correlation result, we can state that this kind of data exploration requires much more data than we currently have. If you want to contribute, just ",
        "stats-page-conclusion-link":        "download",
        "stats-page-conclusion-desc-after":  " the game.",
        "stats-page-controls-header":    "Stats controls",
        "stats-page-refresh-button":     "Refresh",
        "stats-page-filter-label":       "Filter by:",
        "stats-page-filter-placeholder": "Enter nickname or date/time",
        "stats-page-find-button":        "Find",
        "stats-page-th-player":          "PLAYER",
        "stats-page-th-game":            "GAME",
        "stats-page-th-outcome":         "OUTCOME",
        "stats-page-th-duration":        "DURATION (s)",
        "stats-page-th-outlier":         "OUTLIER",
        "stats-page-loading-note":       "Loading... Please wait",

        "home-page-hero-subtitle":   "The ancient board game, reborn online",
        "home-page-hero-desc":       "Conquer the board. Zaroc brings the classic strategy experience to your device.",
        "home-page-hero-cta":        "PLAY NOW",
        "home-page-about-header":    "What is Zaroc?",
        "home-page-about-desc": "Zaroc is a strategy game for 2 players.\nYour pieces start at the top of tall pegs at the back of the board.\nThe goal is to work your way down to the lowest pegs and jump off at the right moment to claim three winning spots.",
        "home-page-features-header": "Why play Zaroc?",
        "home-page-feature-1-title": "Strategic depth",
        "home-page-feature-1-desc":  "Every move matters. Plan ahead or be outmaneuvered.",
        "home-page-feature-2-title": "True to the original",
        "home-page-feature-2-desc":  "Faithful to the board game rules.",
        "home-page-feature-3-title": "Easy to use",
        "home-page-feature-3-desc":  "Clean UI, everyone's must have.",
    },
    NL: {
        "menu-item-home":           "Start",
        "menu-item-team":           "Team",
        "menu-item-gallery":        "Galerij",
        "menu-item-guidelines":     "Richtlijnen",
        "menu-item-implementation": "Uitvoering",
        "menu-item-ai":             "AI",
        "menu-item-stats":          "Statistieken",
        "menu-item-feedback":       "Feedback",

        "team-page-header":                       "Ons Team",
        "team-page-yurii-desc": "Speciale vaardigheid: \n \n Was het oneens met de compiler. \n De compiler had het mis.",
        "team-page-taras-desc": "Speciale vaardigheid: \n \n Ooit een bug opgelost door er lang genoeg naar te staren.",
        "team-page-omer-desc": "Speciale vaardigheid: \n \n Heeft de documentatie nooit gelezen. \n Had dat nooit nodig.",
        "team-page-ronan-desc": "Speciale vaardigheid: \n \n Typt erg snel. \n Dit heeft aantoonbaar niet geholpen.",
        "team-page-decision-insights-header":     "Team inzicht",
        "team-page-decision-insights":            "We dragen allemaal een bril om slim te lijken.",
        "team-page-decision-decisions-header":    "Hoe we beslissingen nemen",
        "team-page-decision-decisions":           "Meestal gooien we gewoon een dobbelsteen, en nemen we daarna een beslissing over het project. We vonden deze aanpak veel makkelijker dan lange discussies.",
        "team-page-decision-working-flow-header": "Werkwijze",
        "team-page-decision-working-flow":        "We openen onze laptops, staren een tijdje naar het scherm, en uiteindelijk werkt er iets. We hebben nog niet uitgevogeld waarom.",
        "team-page-how-made-header": "Hoe we ons project maken",

        "ai-logic-page-header":            "Hoe hebben we het mogelijk gemaakt?",
        "ai-logic-page-approaches-header": "Benaderingen",
        "ai-logic-page-smart-header":      "SLIM",
        "ai-logic-page-smart-list-item-1": "Gecompliceerd algoritme erachter",
        "ai-logic-page-smart-list-item-2": "Complexe kansberekeningen gebaseerd op risicoanalyse",
        "ai-logic-page-smart-list-item-3": "Toekomstvoorspelling",
        "ai-logic-page-smart-list-item-4": "Gebruikt in competitieve en aangepaste wedstrijden",
        "ai-logic-page-smart-list-item-5": "Winnen of verliezen in competitief beïnvloedt het klassement",
        "ai-logic-page-smart-list-item-6": "Bereid jezelf voor in een niet-gerangschikte simulatie",
        "ai-logic-page-random-header":     "WILLEKEURIG",
        "ai-logic-page-random-list-item-1": "Validatie-zet algoritme",
        "ai-logic-page-random-list-item-2": "Pure entropie",
        "ai-logic-page-random-list-item-3": "De meest onverwachte beslissingen",
        "ai-logic-page-random-list-item-4": "Voornamelijk voor de lol gemaakt",
        "ai-logic-page-random-list-item-5": "Heeft geen invloed op je score",
        "ai-logic-page-random-list-item-6": "Alleen beschikbaar in aangepaste wedstrijd",

        "implementation-page-header":       "Implementatie",
        "implementation-page-intro":        "Ons spel werd geimplementeerd als een JavaFX-applicatie in overeenstemming met de MVP-patronen.",
        "implementation-page-domain-header": "Domeinmodel",
        "implementation-page-domain-desc":  "Het domeinmodel toont een overzicht van ons model.",
        "implementation-page-resources-header": "Gebruikte bronnen en expertise",
        "implementation-page-resources-dt-1": "Spelontwerp en balancering",
        "implementation-page-resources-dd-1": "We hebben de bordspelregels omgezet in duidelijke digitale regels en ervoor gezorgd dat randgevallen het spel niet breken.",
        "implementation-page-resources-dt-2": "Objectgeorienteerd programmeren",
        "implementation-page-resources-dd-2": "We hebben de code opgesplitst in objecten met verantwoordelijkheden, zodat de zet-logica, puntentelling en AI makkelijker te lezen en bij te werken zijn.",
        "implementation-page-resources-dt-3": "Gegevensverwerking",
        "implementation-page-resources-dd-3": "Spelresultaten en zetten worden op een gestructureerde manier opgeslagen, waardoor we de statistiekenweergave op de website en het klassement in het spel kunnen bouwen.",
        "implementation-page-notes-header": "Implementatienotities",
        "implementation-page-notes-p1":     "Slimme AI werd geimplementeerd om de speler uit te dagen, terwijl de eenvoudige AI volledig onvoorspelbaar is en gebruikt kan worden om het spel beter te leren kennen.",
        "implementation-page-notes-p2":     "Zetten worden gestructureerd gelogd zodat ze naar de webpagina \"Statistieken\" kunnen worden gestuurd.",

        "feedback-page-header":            "Feedback",
        "feedback-page-intro":             "We zijn eerstejaars studenten die de feedback die we van u krijgen erg waarderen. Als u suggesties of feedback heeft over ons spel of onze website, horen we dat graag. Bedankt en veel plezier.",
        "feedback-page-form-header":       "Geef feedback",
        "feedback-page-legend-personal":   "Persoonlijke informatie",
        "feedback-page-label-name":        "Naam:",
        "feedback-page-placeholder-name":  "bijv. Jan Janssen",
        "feedback-page-label-phone":       "Telefoonnummer:",
        "feedback-page-placeholder-phone": "bijv. +32 123 45 67 89",
        "feedback-page-label-email":       "E-mailadres:",
        "feedback-page-placeholder-email": "bijv. info@zaroc.com",
        "feedback-page-legend-feedback":   "Uw feedback",
        "feedback-page-label-type":        "Waarover gaat de feedback?",
        "feedback-page-option-gameplay":   "Gameplay",
        "feedback-page-option-website":    "Website",
        "feedback-page-option-other":      "Overige",
        "feedback-page-label-feedback":    "Feedback:",
        "feedback-page-submit":            "Versturen",

        "gallery-page-header":    "Screenshots & Media",
        "gallery-page-caption-1": "De rust voor de storm.",
        "gallery-page-caption-2": "Kies je gif",
        "gallery-page-caption-3": "Captcha inbegrepen",
        "gallery-page-caption-4": "Kun jij de top bereiken?",
        "gallery-page-caption-5": "Het is geen geluk. (Het is geluk.)",
        "gallery-page-caption-6": "Om je aan je mislukkingen te herinneren",
        "gallery-page-alt-1":     "inlogscherm",
        "gallery-page-alt-2":     "spelkeuze",
        "gallery-page-alt-3":     "inlogscherm",
        "gallery-page-alt-4":     "klassement",
        "gallery-page-alt-5":     "spelscherm",
        "gallery-page-alt-6":     "spelenoverzicht",

        "guidelines-page-game-rules-header":    "Spelregels",
        "guidelines-page-setup-header":         "Het begin van het spel",
        "guidelines-page-setup-desc":           "Het bord heeft drie rijen pinnen: 5 korte, 4 middelgrote en 4 lange. Druk ze van voor naar achter in hun rijen. Rijg alle 16 stukken op de 4 lange pinnen, afwisselend donker en licht, 4 stukken per pin.",
        "guidelines-page-objective-header":     "Doel",
        "guidelines-page-objective-desc":       "Wees de eerste speler die minstens 3 stukken van jouw kleur in de 5 uitsparingen aan de voorkant van het bord krijgt.",
        "guidelines-page-how-to-play-header":   "Hoe speel je",
        "guidelines-page-how-dt-1":             "De kleur van de stukken maakt niet uit!",
        "guidelines-page-how-dd-1":             "Elke beurt bestaat uit precies twee zetten. Je kunt stukken van beide kleuren verplaatsen tijdens jouw beurt.",
        "guidelines-page-how-dt-2":             "Zijwaartse zet",
        "guidelines-page-how-dd-2":             "Verplaats het bovenste stuk naar een aangrenzende pin van dezelfde hoogte, zolang er ruimte is. Je kunt de zet die je net hebt gedaan niet onmiddellijk ongedaan maken.",
        "guidelines-page-how-dt-3":             "Hoe beweeg je naar voren?",
        "guidelines-page-how-dd-3":             "Verplaats het bovenste stuk naar voren naar een lagere pin of uitsparing, volgens de pijlen op het bord. Dit is alleen toegestaan als het stuk helemaal bovenaan zijn pin staat zonder ruimte erboven.",
        "guidelines-page-how-dt-4":             "Terug in de tijd!",
        "guidelines-page-how-dd-4":             "Je kunt je zet ongedaan maken! Wees je ervan bewust dat je slechts 3 terugnames per spel hebt. Het niet gebruiken van terugnames verhoogt de punten die je krijgt of verliest",
        "guidelines-page-restrictions-header":  "Beperkingen",
        "guidelines-page-restrictions-li-1":    "Zodra een stuk de voorste uitsparingen bereikt, kan het niet meer bewegen.",
        "guidelines-page-restrictions-li-2":    "Achterwaartse zetten zijn niet toegestaan.",
        "guidelines-page-restrictions-li-3":    "Het laatste verplaatste stuk kan niet terug worden gezet naar waar het vandaan kwam, ook niet door de andere speler.",
        "guidelines-page-winning-header":       "Winnen",
        "guidelines-page-winning-desc":         "De eerste speler die 3 stukken van hun kleur in de voorste uitsparingen heeft, wint het spel.",
        "guidelines-page-installation-header":  "Installatie-instructies",
        "guidelines-page-installation-li-1":    "Open je browser (Je bent hier)",
        "guidelines-page-installation-li-2":    "Navigeer naar de hoofdpagina (Nadat je alle instructies hebt gelezen)",
        "guidelines-page-installation-li-3":    "Download het spel en open het",
        "guidelines-page-installation-li-4":    "Ga verder als gast of registreer een account voor meer ervaring",
        "guidelines-page-installation-li-5":    "Veel plezier!",
        "guidelines-page-technical-header":     "Technische vereisten",
        "guidelines-page-technical-dt-1":       "Computer",
        "guidelines-page-technical-dd-1":       "Het spel is alleen beschikbaar voor pc-gebruikers",
        "guidelines-page-technical-dt-2":       "JVM",
        "guidelines-page-technical-dd-2":       "Je moet Java Virtual Machine op je pc geinstalleerd hebben",
        "guidelines-page-technical-dt-3":       "Internetverbinding",
        "guidelines-page-technical-dd-3":       "Geen essentieel vereiste, maar wel nodig als je deel wilt uitmaken van het klassement en je voortgang en instellingen wilt opslaan",

        "stats-page-analysis-header":     "Gegevens analyseren",
        "stats-page-analysis-desc":       "We hebben bepaalde informatie verzameld over de speelstijl van spelers en regressie- en correlatieanalyse uitgevoerd",
        "stats-page-workflow-caption":    "Visuele weergave van het gegevensverkenningsmodel",
        "stats-page-correlation-caption": "Visuele weergave van correlatie",
        "stats-page-numbers-dt":          "Wat vertellen de cijfers ons?",
        "stats-page-numbers-dd":          "Een RMSE boven 65 wijst op grote gegevensspreiding, wat bevestigd wordt door de correlatie- en regressiemodellen.",
        "stats-page-notes-dt":            "Interessante opmerkingen",
        "stats-page-notes-dd":            "De dataset omvat 50 spellen maar slechts 5 spelers, wat de schaalbaarheid beperkt. Het model zonder uitschieters heeft ondanks een lagere correlatieratio een hogere R² en is daardoor representatiever.",
        "stats-page-conclusion-header":   "Conclusie",
        "stats-page-conclusion-desc-before": "Er is geen sterk verband tussen de vaardigheid van de speler en de tijd om een zet te doen. Na onderzoek naar de oorzaken van dit correlatieresultaat kunnen we stellen dat dit soort gegevensverkenning veel meer data vereist dan we momenteel hebben. Als je wilt bijdragen, ",
        "stats-page-conclusion-link":        "download",
        "stats-page-conclusion-desc-after":  " dan het spel.",
        "stats-page-controls-header":    "Statistieken beheer",
        "stats-page-refresh-button":     "Vernieuwen",
        "stats-page-filter-label":       "Filteren op:",
        "stats-page-filter-placeholder": "Voer een bijnaam of datum/tijd in",
        "stats-page-find-button":        "Zoeken",
        "stats-page-th-player":          "Speler",
        "stats-page-th-game":            "Spel",
        "stats-page-th-outcome":         "Resultaat",
        "stats-page-th-duration":        "Duur (s)",
        "stats-page-th-outlier":         "Uitschieter",
        "stats-page-loading-note":       "Laden... Een moment geduld",

        "home-page-hero-subtitle":   "Het oude bordspel, opnieuw geboren online",
        "home-page-hero-desc":       "Verover het bord. Zaroc brengt de klassieke strategiebeleving naar jouw apparaat.",
        "home-page-hero-cta":        "SPEEL NU",
        "home-page-about-header":    "Wat is Zaroc?",
        "home-page-about-desc": "Zaroc is een strategiespel voor 2 spelers.\nJe stukken starten bovenaan hoge pinnen aan de achterkant van het bord.\nHet doel is om naar beneden te werken en op het juiste moment af te springen om drie winnende plekken te claimen.",
        "home-page-features-header": "Waarom Zaroc spelen?",
        "home-page-feature-1-title": "Strategische diepgang",
        "home-page-feature-1-desc":  "Elke zet telt. Plan vooruit of word overtroffen.",
        "home-page-feature-2-title": "Trouw aan het origineel",
        "home-page-feature-2-desc":  "Trouw aan de bordspelregels.",
        "home-page-feature-3-title": "Eenvoudig in gebruik",
        "home-page-feature-3-desc":  "Overzichtelijke interface, een must voor iedereen.",
    },
    FR: {
        "menu-item-home":           "Accueil",
        "menu-item-team":           "Équipe",
        "menu-item-gallery":        "Galerie",
        "menu-item-guidelines":     "Directives",
        "menu-item-implementation": "Mise en œuvre",
        "menu-item-ai":             "IA",
        "menu-item-stats":          "Statistiques",
        "menu-item-feedback":       "Commentaires",

        "team-page-header":                       "Notre Équipe",
        "team-page-yurii-desc": "Compétence spéciale : \n \n En désaccord avec le compilateur. \n Le compilateur avait tort.",
        "team-page-taras-desc": "Compétence spéciale : \n \n A un jour corrigé un bug en le fixant suffisamment longtemps.",
        "team-page-omer-desc": "Compétence spéciale : \n \n N'a jamais lu la documentation. \n N'en a jamais eu besoin.",
        "team-page-ronan-desc": "Compétence spéciale : \n \n Tape très vite. \n Cela n'a pas été prouvé utile.",
        "team-page-decision-insights-header":     "Aperçu de l'équipe",
        "team-page-decision-insights":            "Nous portons tous des lunettes pour avoir l'air intelligent.",
        "team-page-decision-decisions-header":    "Notre façon de prendre des décisions",
        "team-page-decision-decisions":           "En général, on lance un dé, puis on prend une décision sur le projet en conséquence. Nous avons trouvé cette approche bien plus simple que de longues discussions.",
        "team-page-decision-working-flow-header": "Flux de travail",
        "team-page-decision-working-flow":        "Nous ouvrons nos ordinateurs, fixons l'écran un moment, et finalement quelque chose fonctionne. Nous n'avons pas encore compris pourquoi.",
        "team-page-how-made-header": "Comment nous réalisons notre projet",

        "ai-logic-page-header":            "Comment l'avons-nous rendu possible ?",
        "ai-logic-page-approaches-header": "Approches",
        "ai-logic-page-smart-header":      "INTELLIGENT",
        "ai-logic-page-smart-list-item-1": "Algorithme complexe en coulisse",
        "ai-logic-page-smart-list-item-2": "Calculs de probabilité complexes basés sur l'évaluation des risques",
        "ai-logic-page-smart-list-item-3": "Prédiction du futur",
        "ai-logic-page-smart-list-item-4": "Utilisé dans les matchs compétitifs et personnalisés",
        "ai-logic-page-smart-list-item-5": "Gagner ou perdre en compétitif affecte le classement",
        "ai-logic-page-smart-list-item-6": "Entraînez-vous dans une simulation non classée",
        "ai-logic-page-random-header":     "ALÉATOIRE",
        "ai-logic-page-random-list-item-1": "Algorithme de validation de coup",
        "ai-logic-page-random-list-item-2": "Entropie pure",
        "ai-logic-page-random-list-item-3": "Les décisions les plus inattendues",
        "ai-logic-page-random-list-item-4": "Créé surtout pour s'amuser",
        "ai-logic-page-random-list-item-5": "N'a aucun impact sur votre score",
        "ai-logic-page-random-list-item-6": "Disponible uniquement en match personnalisé",

        "implementation-page-header":       "Mise en oeuvre",
        "implementation-page-intro":        "Notre jeu a ete mis en oeuvre en tant qu'application JavaFX conformement aux patrons MVP.",
        "implementation-page-domain-header": "Modele de domaine",
        "implementation-page-domain-desc":  "Le modele de domaine montre une vue d'ensemble de notre modele.",
        "implementation-page-resources-header": "Ressources et expertise utilisees",
        "implementation-page-resources-dt-1": "Conception et equilibrage du jeu",
        "implementation-page-resources-dd-1": "Nous avons transforme les regles du jeu de plateau en regles numeriques claires et veille a ce que les cas limites ne brisent pas le jeu.",
        "implementation-page-resources-dt-2": "Programmation orientee objet",
        "implementation-page-resources-dd-2": "Nous avons separe le code en objets avec des responsabilites, afin que la logique des coups, le score et l'IA soient plus faciles a lire et a mettre a jour.",
        "implementation-page-resources-dt-3": "Gestion des donnees",
        "implementation-page-resources-dd-3": "Les resultats de jeu et les coups sont stockes de maniere structuree, ce qui nous permet de construire la vue des statistiques sur le site et le classement en jeu.",
        "implementation-page-notes-header": "Notes de mise en oeuvre",
        "implementation-page-notes-p1":     "L'IA intelligente a ete mise en oeuvre pour defier le joueur, tandis que l'IA facile est completement impredictible et peut etre utilisee pour mieux connaitre le jeu.",
        "implementation-page-notes-p2":     "Les coups sont enregistres de maniere structuree afin de pouvoir etre envoyes a la page web \"Statistiques\".",

        "feedback-page-header":            "Commentaires",
        "feedback-page-intro":             "Nous sommes des etudiants de premiere annee qui accordons beaucoup de valeur aux retours que nous recevons. Si vous avez des suggestions ou des commentaires concernant notre jeu ou notre site web, nous serions ravis de les entendre. Merci et amusez-vous bien.",
        "feedback-page-form-header":       "Donnez votre avis",
        "feedback-page-legend-personal":   "Informations personnelles",
        "feedback-page-label-name":        "Nom :",
        "feedback-page-placeholder-name":  "ex. Jean Dupont",
        "feedback-page-label-phone":       "Numero de telephone :",
        "feedback-page-placeholder-phone": "ex. +32 123 45 67 89",
        "feedback-page-label-email":       "Adresse e-mail :",
        "feedback-page-placeholder-email": "ex. info@zaroc.com",
        "feedback-page-legend-feedback":   "Votre avis",
        "feedback-page-label-type":        "Sur quoi porte votre avis ?",
        "feedback-page-option-gameplay":   "Gameplay",
        "feedback-page-option-website":    "Site web",
        "feedback-page-option-other":      "Autre",
        "feedback-page-label-feedback":    "Commentaire :",
        "feedback-page-submit":            "Envoyer",

        "gallery-page-header":    "Captures d'ecran et media",
        "gallery-page-caption-1": "Le calme avant la tempete.",
        "gallery-page-caption-2": "Choisissez votre poison",
        "gallery-page-caption-3": "Captcha inclus",
        "gallery-page-caption-4": "Pouvez-vous atteindre le sommet ?",
        "gallery-page-caption-5": "Ce n'est pas de la chance. (C'est de la chance.)",
        "gallery-page-caption-6": "Pour se souvenir de ses echecs",
        "gallery-page-alt-1":     "ecran de connexion",
        "gallery-page-alt-2":     "selection de jeu",
        "gallery-page-alt-3":     "ecran de connexion",
        "gallery-page-alt-4":     "classement",
        "gallery-page-alt-5":     "ecran de jeu",
        "gallery-page-alt-6":     "apercu des parties",

        "guidelines-page-game-rules-header":    "Règles du jeu",
        "guidelines-page-setup-header":         "Le début de la partie",
        "guidelines-page-setup-desc":           "Le plateau comporte trois rangées de chevilles : 5 courtes, 4 moyennes et 4 longues. Enfoncez-les dans leurs rangées de l'avant vers l'arrière. Enfilez les 16 pièces sur les 4 longues chevilles, en alternant clair et foncé, 4 pièces par cheville.",
        "guidelines-page-objective-header":     "Objectif",
        "guidelines-page-objective-desc":       "Soyez le premier joueur à placer au moins 3 pièces de votre couleur dans les 5 emplacements à l'avant du plateau.",
        "guidelines-page-how-to-play-header":   "Comment jouer",
        "guidelines-page-how-dt-1":             "La couleur des pièces n'a pas d'importance !",
        "guidelines-page-how-dd-1":             "Chaque tour se compose exactement de deux coups. Vous pouvez déplacer des pièces des deux couleurs pendant votre tour.",
        "guidelines-page-how-dt-2":             "Déplacement latéral",
        "guidelines-page-how-dd-2":             "Déplacez la pièce du dessus vers une cheville adjacente de même hauteur, à condition qu'il y ait de la place. Vous ne pouvez pas annuler immédiatement le coup que vous venez de faire.",
        "guidelines-page-how-dt-3":             "Comment avancer ?",
        "guidelines-page-how-dd-3":             "Déplacez la pièce du dessus vers l'avant sur une cheville ou un emplacement plus bas, en suivant les flèches sur le plateau. Cela n'est autorisé que si la pièce se trouve tout en haut de sa cheville sans espace au-dessus.",
        "guidelines-page-how-dt-4":             "Retour dans le temps !",
        "guidelines-page-how-dd-4":             "Vous pouvez annuler votre coup ! Sachez que vous n'avez que 3 annulations par partie. Ne pas utiliser d'annulations augmente les points que vous gagnez ou perdez",
        "guidelines-page-restrictions-header":  "Restrictions",
        "guidelines-page-restrictions-li-1":    "Une fois qu'une pièce atteint les emplacements avant, elle ne peut plus bouger.",
        "guidelines-page-restrictions-li-2":    "Les déplacements en arrière ne sont pas autorisés.",
        "guidelines-page-restrictions-li-3":    "La dernière pièce déplacée ne peut pas être remise à son emplacement d'origine, même par l'autre joueur.",
        "guidelines-page-winning-header":       "Victoire",
        "guidelines-page-winning-desc":         "Le premier joueur à avoir 3 pièces de sa couleur dans les emplacements avant gagne la partie.",
        "guidelines-page-installation-header":  "Instructions d'installation",
        "guidelines-page-installation-li-1":    "Ouvrez votre navigateur (Vous êtes ici)",
        "guidelines-page-installation-li-2":    "Accédez à la page principale (Après avoir lu toutes les instructions)",
        "guidelines-page-installation-li-3":    "Téléchargez le jeu et ouvrez-le",
        "guidelines-page-installation-li-4":    "Continuez en tant qu'invité ou créez un compte pour plus d'expérience",
        "guidelines-page-installation-li-5":    "Amusez-vous bien !",
        "guidelines-page-technical-header":     "Configuration requise",
        "guidelines-page-technical-dt-1":       "Ordinateur",
        "guidelines-page-technical-dd-1":       "Le jeu est uniquement disponible pour les utilisateurs PC",
        "guidelines-page-technical-dt-2":       "JVM",
        "guidelines-page-technical-dd-2":       "Vous devez avoir la machine virtuelle Java installée sur votre PC",
        "guidelines-page-technical-dt-3":       "Connexion Internet",
        "guidelines-page-technical-dd-3":       "Exigence non essentielle, mais nécessaire si vous souhaitez figurer au classement et sauvegarder votre progression ainsi que vos paramètres",

        "stats-page-analysis-header":     "Analyse des données",
        "stats-page-analysis-desc":       "Nous avons collecté certaines informations sur le style de jeu des joueurs et effectué des analyses de régression et de corrélation",
        "stats-page-workflow-caption":    "Représentation visuelle du modèle d'exploration des données",
        "stats-page-correlation-caption": "Représentation visuelle de la corrélation",
        "stats-page-numbers-dt":          "Que nous disent les chiffres ?",
        "stats-page-numbers-dd":          "Un RMSE supérieur à 65 indique une forte dispersion des données, ce qui est confirmé par les modèles de corrélation et de régression.",
        "stats-page-notes-dt":            "Remarques intéressantes",
        "stats-page-notes-dd":            "Le jeu de données couvre 50 parties mais seulement 5 joueurs, ce qui limite sa scalabilité. Le modèle sans valeurs aberrantes, malgré un ratio de corrélation plus faible, a un R² plus élevé et est donc plus représentatif.",
        "stats-page-conclusion-header":   "Conclusion",
        "stats-page-conclusion-desc-before": "Il n'existe pas de corrélation forte entre le niveau du joueur et le temps pour effectuer un coup. Après avoir étudié les causes de ce résultat, nous pouvons affirmer que ce type d'exploration de données nécessite bien plus de données que nous n'en avons actuellement. Si vous souhaitez contribuer, ",
        "stats-page-conclusion-link":        "téléchargez",
        "stats-page-conclusion-desc-after":  " simplement le jeu.",
        "stats-page-controls-header":    "Controles des statistiques",
        "stats-page-refresh-button":     "Actualiser",
        "stats-page-filter-label":       "Filtrer par :",
        "stats-page-filter-placeholder": "Entrez un pseudo ou une date/heure",
        "stats-page-find-button":        "Rechercher",
        "stats-page-th-player":          "Joueur",
        "stats-page-th-game":            "Partie",
        "stats-page-th-outcome":         "Resultat",
        "stats-page-th-duration":        "Duree (s)",
        "stats-page-th-outlier":         "Valeur aberrante",
        "stats-page-loading-note":       "Chargement... Veuillez patienter",

        "home-page-hero-subtitle":   "L'ancien jeu de plateau, reborn en ligne",
        "home-page-hero-desc":       "Conquérez le plateau. Zaroc apporte l'expérience stratégique classique sur votre appareil.",
        "home-page-hero-cta":        "JOUER MAINTENANT",
        "home-page-about-header":    "Qu'est-ce que Zaroc ?",
        "home-page-about-desc": "Zaroc est un jeu de stratégie pour 2 joueurs.\nVos pièces démarrent en haut de grandes chevilles à l'arrière du plateau.\nL'objectif est de descendre jusqu'aux chevilles les plus basses et de sauter au bon moment pour revendiquer trois emplacements gagnants.",
        "home-page-features-header": "Pourquoi jouer à Zaroc ?",
        "home-page-feature-1-title": "Profondeur stratégique",
        "home-page-feature-1-desc":  "Chaque coup compte. Anticipez ou soyez dépassé.",
        "home-page-feature-2-title": "Fidèle à l'original",
        "home-page-feature-2-desc":  "Respecte les règles du jeu de plateau.",
        "home-page-feature-3-title": "Facile à utiliser",
        "home-page-feature-3-desc":  "Interface épurée, indispensable pour tous.",
    }
}
